### ISSUE TITLE
Cursor Position is incorrect when CSS Zoom is applied to container

### ISSUE THREAD

**Issue by ashitvora** [ajaxorg/ace-builds#114] opened 2017-08-08 05:39 UTC
I'm using Ace Editor in my App and when CSS zoom is applied to the container div, the cursor position is positioned incorrectly. when I start typing, it types at a different place than where the cursor is.
But when the zoom is brought back to normal, the cursor is positioned correctly.

I searched for this issue and most of the solutions are related to setting monospaced font and not setting letter spacing to 0. I checked both of them and they are correct.

**Comment by ashitvora** [comment] 2017-09-13 06:59
Any updates on this issue?
Anybody was able to solve this?

**Comment by nightwing** [comment] 2017-09-14 06:03
Are you using https://developer.mozilla.org/en-US/docs/Web/CSS/zoom? it seems to be a non standard property, and is not supported by all browsers.
I think this is a duplicate of https://github.com/ajaxorg/ace/issues/2475

**Closed** 2017-09-14 06:46 UTC
