### ISSUE TITLE
JSLint error in noconflict's worker-coffee.js

### ISSUE THREAD

**Issue by ervumlens** [ajaxorg/ace-builds#61] opened 2015-07-16 19:45 UTC
I'm getting a JSLint error on [line 1411 of worker-coffee.js](https://github.com/ajaxorg/ace-builds/blob/master/src-noconflict/worker-coffee.js#L1411) in the `src-noconflict` build. I don't have a use-case to test for a specific problem.

**worker-coffee.js @ 1411**
```javascript
function ace.define(f) { module.exports = f() }; define.amd = {};
```
**Error**
> SyntaxError: missing ( before formal parameters: (on column 13) 

Running the line in isolation at [javascriptlint.com](http://javascriptlint.com/online_lint.php) gives me the following:

```
	
Results
1  function ace.define(f) { module.exports = f() }; define.amd = {};
   ============^
   SyntaxError: missing ( before formal parameters
```

I might be missing something. I do that sometimes.

P.S. I'm logging this here rather than in ace itself because I can't find the corresponding code there.

**Comment by nightwing** [comment] 2015-07-17 08:58
Thanks for detailed bug report.
This is caused by https://github.com/ajaxorg/ace/blob/master/Makefile.dryice.js#L474. It should not change the line `function define(f)`. Until this is fixed please use https://github.com/ajaxorg/ace-builds/blob/master/src/ace.js instead of src-noconflict.

**Comment by nightwing** [comment] 2015-09-29 20:35
this is fixed now

**Closed by nightwing** 2015-09-29 20:35 UTC
