### ISSUE TITLE
Unable to load theme and apply css using ace-builds/src-noconflict/ext-static_highlight.js when we have two themes to be loaded parallely

### ISSUE THREAD

**Issue by lavanyaburlagadda1807** [ajaxorg/ace-builds#257] opened 2023-10-29 13:49 UTC
I have an use cases where I need to show HTML code using monokai theme and CSS and Javascript using Dracula theme.

These styles should be applied dynalically using [ace-builds](https://unpkg.com/browse/ace-builds@1.3.0/)/[src-noconflict](https://unpkg.com/browse/ace-builds@1.3.0/src-noconflict/)/ext-static_highlight.js

But because of loading two themes parallely I am getting the issue.

Code we used for highlighting

```
export const getTheme = language => {
   if (language === codeLanguage.html) {
      return 'monokai'
   }
   return 'dracula'
}

export const setStaticSyntaxHighlighting = (
   className: string,
   aceMode: string
) => {
   let highlight = require('ace-builds/src-noconflict/ext-static_highlight')

   const qsa = sel => {
      //@ts-ignore
      return Array.apply(null, document.querySelectorAll(sel))
   }
   qsa(`.${className}`).forEach(codeEl => {
      highlight(
         codeEl,
         {
            mode: `ace/mode/${getEditorMode(aceMode)}`,
            theme: `ace/theme/${getTheme(aceMode)}`,
            startLineNumber: 1,
            //@ts-ignore
            showGutter: codeEl.getAttribute('ace-gutter'),
            trim: true
         },
         function(highlighted) {}
      )
   })
}


```
![image](https://github.com/ajaxorg/ace-builds/assets/140611388/6bc91222-753a-4ab4-945f-2d5923265721)
For CSS it applied properly 
![image](https://github.com/ajaxorg/ace-builds/assets/140611388/f82ed701-d5fa-49c4-9243-fd8e968b6d97)
But for HTML it didn't worked

Someone please look into the issue and provide me solution

**Comment by nightwing** [comment] 2023-10-29 19:39
This is caused by lazy loading of css for pages using CSP, this will be fixed in the next version, but in meantime you can use the following line `ace.require("ace/lib/dom").importCssString("","", true)` as a workdaround [example here](https://mkslanc.github.io/ace-playground/?value=YWNlLnJlcXVpcmUoImFjZS9saWIvZG9tIikuaW1wb3J0Q3NzU3RyaW5nKCIiLCIiLCB0cnVlKQ0KDQp2YXIgZ2V0VGhlbWUgPSBsYW5ndWFnZSA9PiB7DQogICBpZiAobGFuZ3VhZ2UgPT09ICJodG1sIikgew0KICAgICAgcmV0dXJuICdtb25va2FpJw0KICAgfQ0KICAgcmV0dXJuICdkcmFjdWxhJw0KfQ0KDQpsZXQgaGlnaGxpZ2h0ID0gYWNlLnJlcXVpcmUoJ2FjZS9leHQvc3RhdGljX2hpZ2hsaWdodCcpDQoNCg0KdmFyIHNldFN0YXRpY1N5bnRheEhpZ2hsaWdodGluZyA9IChjbGFzc05hbWUsIGFjZU1vZGUpID0%2BIHsNCg0KICAgdmFyIHFzYSA9IHNlbCA9PiB7DQogICAgICByZXR1cm4gQXJyYXkuYXBwbHkobnVsbCwgZG9jdW1lbnQucXVlcnlTZWxlY3RvckFsbChzZWwpKQ0KICAgfQ0KICAgcXNhKGAuJHtjbGFzc05hbWV9YCkuZm9yRWFjaChjb2RlRWwgPT4gew0KICAgICAgaGlnaGxpZ2h0KA0KICAgICAgICAgY29kZUVsLA0KICAgICAgICAgew0KICAgICAgICAgICAgbW9kZTogYGFjZS9tb2RlLyR7YWNlTW9kZX1gLA0KICAgICAgICAgICAgdGhlbWU6IGBhY2UvdGhlbWUvJHtnZXRUaGVtZShhY2VNb2RlKX1gLA0KICAgICAgICAgICAgc3RhcnRMaW5lTnVtYmVyOiAxLA0KICAgICAgICAgICAgLy9AdHMtaWdub3JlDQogICAgICAgICAgICBzaG93R3V0dGVyOiB0cnVlLA0KICAgICAgICAgICAgdHJpbTogdHJ1ZQ0KICAgICAgICAgfSwNCiAgICAgICAgIGZ1bmN0aW9uKGhpZ2hsaWdodGVkKSB7fQ0KICAgICAgKQ0KICAgfSkNCn0NCg0Kc2V0U3RhdGljU3ludGF4SGlnaGxpZ2h0aW5nKCJjb2RlSHRtbCIsICJodG1sIikNCnNldFN0YXRpY1N5bnRheEhpZ2hsaWdodGluZygiY29kZUpzIiwgImphdmFzY3JpcHQiKVwwKnsKICAgIGNvbG9yOiByZWQ7Cn1cMDxzY3JpcHQgc3JjPSJodHRwczovL3d3dy51bnBrZy5jb20vYWNlLWJ1aWxkc0BsYXRlc3Qvc3JjLW5vY29uZmxpY3QvYWNlLmpzIj48L3NjcmlwdD4KPHNjcmlwdCBzcmM9Imh0dHBzOi8vd3d3LnVucGtnLmNvbS9hY2UtYnVpbGRzQGxhdGVzdC9zcmMtbm9jb25mbGljdC9leHQtc3RhdGljX2hpZ2hsaWdodC5qcyI%2BPC9zY3JpcHQ%2BCgogCjxwcmUgY2xhc3M9ImNvZGVIdG1sIj4KICAgICZsdDtkaXYmZ3Q7ICZsdDtkaXYmZ3Q7CjwvcHJlPgoKPHByZSBjbGFzcz0iY29kZUpzIj4KICAgdmFyIHNvbWVWYXIgPSAianMiCjwvcHJlPg%3D%3D#hello-world)

**Closed** 2023-10-30 09:27 UTC
