### ISSUE TITLE
Invalid Cursor position when Editor is Zoomed

### ISSUE THREAD

**Issue by ashitvora** [ajaxorg/ace-builds#118] opened 2017-09-13 07:25 UTC
I have an SVG canvas which contains Ace Editor in a DIV container.
The application has a feature to zoom in and out which actually zooms the Canvas.
When I zoom in, size of the Ace Editor increases but the cursor position is out of place.
How can this issue be fixed so correct cursor position is calculated?

**Comment by nightwing** [comment] 2017-09-14 06:03
Duplicate of https://github.com/ajaxorg/ace/issues/2475

**Closed by nightwing** 2017-09-14 06:03 UTC
